[workspace]
resolver = "3"
members = ["database", "reverse_cli"]


[workspace.dependencies]
anyhow = "1.0.99"
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
