[package]
name = "reverse_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
database = { path = "../database" }
tokio = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4.5.45", features = ["derive"] }
tera = "1.20.0"
dotenvy = "0.15.7"
heck = "0.5.0"
